const js = require("@eslint/js");
const globals = require("globals");
const prettier = require("eslint-config-prettier/flat");

const rules = {
  "array-callback-return": ["error", { allowImplicit: false, checkForEach: true }],
  "constructor-super": "error",
  "for-direction": "error",
  "getter-return": "error",
  "no-async-promise-executor": "error",
  "no-await-in-loop": "warn",
  "no-class-assign": "error",
  "no-compare-neg-zero": "error",
  "no-cond-assign": ["error", "always"],
  "no-const-assign": "error",
  "no-constant-binary-expression": "error",
  "no-constant-condition": ["error", { checkLoops: false }],
  "no-constructor-return": "error",
  "no-control-regex": "error",
  "no-debugger": "error",
  "no-dupe-args": "error",
  "no-dupe-class-members": "error",
  "no-dupe-else-if": "error",
  "no-dupe-keys": "error",
  "no-duplicate-case": "error",
  "no-duplicate-imports": "error",
  "no-empty-character-class": "error",
  "no-empty-pattern": "error",
  "no-ex-assign": "error",
  "no-fallthrough": "error",
  "no-func-assign": "error",
  "no-import-assign": "error",
  "no-inner-declarations": "error",
  "no-invalid-regexp": "error",
  "no-irregular-whitespace": "error",
  "no-loss-of-precision": "error",
  "no-misleading-character-class": "error",
  "no-new-symbol": "error",
  "no-obj-calls": "error",
  "no-promise-executor-return": "error",
  "no-prototype-builtins": "error",
  "no-self-assign": ["error", { props: true }],
  "no-self-compare": "error",
  "no-setter-return": "error",
  "no-sparse-arrays": "error",
  "no-template-curly-in-string": "error",
  "no-this-before-super": "error",
  "no-undef": "error",
  "no-unexpected-multiline": "error",
  "no-unmodified-loop-condition": "error",
  "no-unreachable": "error",
  "no-unreachable-loop": "error",
  "no-unsafe-finally": "error",
  "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
  "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
  "no-unused-private-class-members": "error",
  "no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
  "no-use-before-define": ["error", { functions: false, classes: true, variables: true }],
  "no-useless-backreference": "error",
  "require-atomic-updates": "error",
  "use-isnan": ["error", { enforceForSwitchCase: true, enforceForIndexOf: true }],
  "valid-typeof": ["error", { requireStringLiterals: true }],

  "accessor-pairs": ["error", { setWithoutGet: true, enforceForClassMembers: true }],
  "arrow-body-style": ["error", "as-needed"],
  "block-scoped-var": "error",
  camelcase: ["error", { properties: "never", ignoreDestructuring: false }],
  "class-methods-use-this": ["warn", { exceptMethods: [] }],
  complexity: "off",
  "consistent-return": ["error", { treatUndefinedAsUnspecified: false }],
  "consistent-this": ["error", "self"],
  curly: ["error", "all"],
  "default-case": ["error", { commentPattern: "^no default$" }],
  "default-case-last": "error",
  "default-param-last": "error",
  "dot-notation": ["error", { allowKeywords: true }],
  eqeqeq: ["error", "always", { null: "ignore" }],
  "func-name-matching": ["error", "always", { considerPropertyDescriptor: true }],
  "func-names": ["error", "as-needed"],
  "func-style": ["error", "declaration", { allowArrowFunctions: true }],
  "grouped-accessor-pairs": ["error", "getBeforeSet"],
  "guard-for-in": "error",
  "id-denylist": ["error", "data", "err", "e", "cb", "callback"],
  "id-length": [
    "error",
    {
      min: 2,
      exceptions: ["i", "j", "k", "_", "x"],
      properties: "never",
    },
  ],
  "init-declarations": ["error", "always"],
  "logical-assignment-operators": ["error", "always"],
  "max-classes-per-file": ["error", 1],
  "max-depth": ["warn", 4],
  "max-lines": ["warn", { max: 1000, skipBlankLines: true, skipComments: true }],
  "max-lines-per-function": "off",
  "max-nested-callbacks": ["error", 3],
  "max-params": ["warn", 3],
  "max-statements": "off",
  "new-cap": ["error", { newIsCap: true, capIsNew: false, properties: true }],
  "no-alert": "warn",
  "no-array-constructor": "error",
  "no-bitwise": "error",
  "no-caller": "error",
  "no-case-declarations": "error",
  "no-console": "warn",
  "no-delete-var": "error",
  "no-div-regex": "error",
  "no-else-return": ["error", { allowElseIf: false }],
  "no-empty": ["error", { allowEmptyCatch: true }],
  "no-empty-function": ["error", { allow: ["arrowFunctions", "functions", "methods"] }],
  "no-eq-null": "off",
  "no-eval": "error",
  "no-extend-native": "error",
  "no-extra-bind": "error",
  "no-extra-boolean-cast": "error",
  "no-extra-label": "error",
  "no-global-assign": "error",
  "no-implicit-coercion": ["error", { boolean: false, number: true, string: true }],
  "no-implicit-globals": ["error", { lexicalBindings: true }],
  "no-implied-eval": "error",
  "no-invalid-this": ["error", { capIsConstructor: false }],
  "no-iterator": "error",
  "no-label-var": "error",
  "no-labels": ["error", { allowLoop: false, allowSwitch: false }],
  "no-lone-blocks": "error",
  "no-lonely-if": "error",
  "no-loop-func": "error",
  "no-magic-numbers": "off",
  "no-multi-assign": ["error", { ignoreNonDeclaration: true }],
  "no-multi-str": "error",
  "no-negated-condition": "error",
  "no-nested-ternary": "error",
  "no-new": "error",
  "no-new-func": "error",
  "no-object-constructor": "error",
  "no-new-object": "error",
  "no-new-wrappers": "error",
  "no-nonoctal-decimal-escape": "error",
  "no-octal": "error",
  "no-octal-escape": "error",
  "no-param-reassign": ["error", { props: true }],
  "no-plusplus": ["error", { allowForLoopAfterthoughts: true }],
  "no-proto": "error",
  "no-redeclare": ["error", { builtinGlobals: true }],
  "no-regex-spaces": "error",
  "no-restricted-exports": ["error", { restrictedNamedExports: ["default", "then"] }],
  "no-restricted-globals": ["error", "isFinite", "isNaN"],
  "no-restricted-imports": ["error", { patterns: ["../*"] }],
  "no-restricted-properties": [
    "error",
    {
      object: "arguments",
      property: "callee",
      message: "arguments.callee is deprecated",
    },
    {
      object: "global",
      property: "isFinite",
      message: "Use Number.isFinite instead",
    },
    {
      object: "self",
      property: "isFinite",
      message: "Use Number.isFinite instead",
    },
    {
      object: "window",
      property: "isFinite",
      message: "Use Number.isFinite instead",
    },
    {
      object: "global",
      property: "isNaN",
      message: "Use Number.isNaN instead",
    },
    {
      object: "self",
      property: "isNaN",
      message: "Use Number.isNaN instead",
    },
    {
      object: "window",
      property: "isNaN",
      message: "Use Number.isNaN instead",
    },
  ],
  "no-restricted-syntax": [
    "error",
    {
      selector: "ForInStatement",
      message:
        "for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.",
    },
    {
      selector: "LabeledStatement",
      message: "Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.",
    },
    {
      selector: "WithStatement",
      message: "`with` is disallowed in strict mode because it makes code impossible to predict and optimize.",
    },
  ],
  "no-return-assign": ["error", "always"],
  "no-return-await": "error",
  "no-script-url": "error",
  "no-sequences": ["error", { allowInParentheses: false }],
  "no-shadow": ["error", { builtinGlobals: false, hoist: "functions", allow: [] }],
  "no-shadow-restricted-names": "error",
  "no-ternary": "off",
  "no-throw-literal": "error",
  "no-undef-init": "error",
  "no-undefined": "error",
  "no-underscore-dangle": [
    "warn",
    {
      allowAfterThis: false,
      allowAfterSuper: false,
      enforceInMethodNames: true,
      allow: ["_config"],
    },
  ],
  "no-unneeded-ternary": ["error", { defaultAssignment: false }],
  "no-unused-expressions": [
    "error",
    {
      allowShortCircuit: false,
      allowTernary: false,
      allowTaggedTemplates: false,
    },
  ],
  "no-useless-call": "error",
  "no-useless-catch": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "off",
  "no-useless-constructor": "error",
  "no-useless-escape": "error",
  "no-useless-rename": [
    "error",
    {
      ignoreDestructuring: false,
      ignoreImport: false,
      ignoreExport: false,
    },
  ],
  "no-useless-return": "error",
  "no-var": "error",
  "no-void": "error",
  "no-warning-comments": ["warn", { terms: ["todo", "fixme", "xxx"], location: "start" }],
  "no-with": "error",
  "object-shorthand": ["error", "always", { ignoreConstructors: false, avoidQuotes: true }],
  "one-var": ["error", "never"],
  "one-var-declaration-per-line": ["error", "always"],
  "operator-assignment": ["error", "always"],
  "prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: true }],
  "prefer-const": ["error", { destructuring: "any", ignoreReadBeforeAssign: true }],
  "prefer-destructuring": [
    "error",
    {
      VariableDeclarator: { array: false, object: true },
      AssignmentExpression: { array: true, object: false },
    },
    { enforceForRenamedProperties: false },
  ],
  "prefer-exponentiation-operator": "error",
  "prefer-named-capture-group": "off",
  "prefer-numeric-literals": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
  "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "quote-props": ["error", "as-needed", { keywords: false, unnecessary: true, numbers: false }],
  radix: "off",
  "require-await": "error",
  "require-unicode-regexp": "off",
  "sort-imports": [
    "error",
    {
      ignoreCase: false,
      ignoreDeclarationSort: false,
      ignoreMemberSort: false,
      memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
      allowSeparatedGroups: false,
    },
  ],
  "sort-keys": ["off", "asc", { caseSensitive: false, natural: true }],
  "sort-vars": "off",
  "spaced-comment": [
    "error",
    "always",
    {
      line: { exceptions: ["-", "+"], markers: ["=", "!", "/"] },
      block: {
        exceptions: ["-", "+"],
        markers: ["=", "!", ":", "::"],
        balanced: true,
      },
    },
  ],
  strict: ["error", "never"],
  "symbol-description": "error",
  "vars-on-top": "error",
  yoda: "error",
};

module.exports = [
  {
    ignores: ["**/*.min.js", "**/node_modules/**"],
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
  },
  {
    files: ["eslint.config.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        ...globals.node,
      },
    },
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        bootstrap: "readonly",
        ...globals.browser,
      },
    },
  },
  js.configs.recommended,
  {
    files: ["**/*.js"],
    rules,
  },
  prettier,
];
