name: "Check spelling"
on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches-ignore:
      - "dependabot/**"

env:
  FORCE_COLOR: 2
  NODE: 16

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: streetsidesoftware/cspell-action@v2
        with:
          check_dot_files: false
          incremental_files_only: true
          inline: warning
          strict: false
